name: Create PR to Quill-Design repo with lastest tailwind config and CSS variables

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'dist/quill-tailwind/**'

jobs:
  pull-request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@master
        with:
          timeZone: UTC
          format: 'YYYY-MM-DD-HH-mm-ss'
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Create pull request
        uses: deriv-com/action-create-pull-request-another-repo@e06bfb57b2d1649909cee2092f4987fedd41e81d
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_folder: 'dist/quill-tailwind'
          destination_repo: 'deriv-com/quill-design'
          destination_base_branch: 'main'
          destination_head_branch: ${{format( 'update-quill-tailwind-config-{0}', steps.time.outputs.time )}}
          user_email: 'mohsen@regentmarkets.com'
          user_name: 'mohsen-deriv'
          commit_message_title: 'chore'
          pull_request_reviewers: 'mohsen-deriv,prince-deriv,yashim-deriv'
