name: Release
on:
  pull_request:
    types: [closed]
    branches: [master]

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Check PR Comments
        id: check-comments
        uses: actions/github-script@v7
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number
            });
            const hasReleaseComment = comments.some(comment => 
              comment.body.toLowerCase().includes('npm-release')
            );
            core.setOutput('has-release-comment', hasReleaseComment);

      - name: Checkout
        if: steps.check-comments.outputs.has-release-comment == 'true'
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        if: steps.check-comments.outputs.has-release-comment == 'true'
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: '20'
          
      - name: Update to latest npm (temporary fix for audit below)
        if: steps.check-comments.outputs.has-release-comment == 'true'
        run: npm install --global npm
        
      - name: Install dependencies
        if: steps.check-comments.outputs.has-release-comment == 'true'
        run: npm clean-install
        
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        if: steps.check-comments.outputs.has-release-comment == 'true'
        run: npm audit signatures
        
      - name: Prepublish
        if: steps.check-comments.outputs.has-release-comment == 'true'
        run: npm run prepublish
        
      - name: Release
        if: steps.check-comments.outputs.has-release-comment == 'true'
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN}}
        run: npx semantic-release